## Use node-modules linker for compatibility with tools (Vite build on GitHub Actions)
## PnP can work, but some ESM resolution inside Vite 7 occasionally breaks under CI
## unless unplugged packages are declared. Simpler: switch to classic node_modules.
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.11.0.cjs
